package com.g2t.footline.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import com.g2t.footline.exception.ArquivoNaoEncontradoException;
import com.g2t.footline.exception.RegistroNaoEncontradoException;
import com.g2t.footline.negocio.Fachada;
import java.awt.Window.Type;

/**
 * @author Taciano
 */
public class FrmOpcao extends javax.swing.JFrame {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 6372065349465603650L;

	/**
	 * Creates new form Principal
	 */
	public FrmOpcao() {
		getContentPane().setEnabled(false);
		setType(Type.UTILITY);
		setResizable(false);
		getContentPane().setBackground(Color.BLACK);
		setBackground(Color.BLACK);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		// btnAtualizar = new javax.swing.JButton();

		try {
			/*
			 * Le os arquivos de selecoes e carrega os 
			 * 	array de selecao e jogador
			 */
			Fachada.getInstance().carregarSelecaoJogador();
		
			// Carrega o array de arbitro
			Fachada.getInstance().carregarArbitro();
			
			// Carrega o array de estadio
			Fachada.getInstance().carregarEstadio();	
			
			Fachada.getInstance().carregarRodadas();
			
			setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	
			JPanel panel = new JPanel();
			panel.setBackground(Color.BLACK);
			panel.setLayout(null);
			GroupLayout groupLayout = new GroupLayout(getContentPane());
			groupLayout.setHorizontalGroup(
				groupLayout.createParallelGroup(Alignment.LEADING)
					.addGroup(groupLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(panel, GroupLayout.PREFERRED_SIZE, 576, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(20, Short.MAX_VALUE))
			);
			groupLayout.setVerticalGroup(
				groupLayout.createParallelGroup(Alignment.LEADING)
					.addGroup(groupLayout.createSequentialGroup()
						.addGap(21)
						.addComponent(panel, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(20, Short.MAX_VALUE))
			);
			
			JButton btnNovo = new JButton();
			btnNovo = new javax.swing.JButton();
			btnNovo.setBounds(409, 28, 147, 90);
			btnNovo.setFont(new Font("Tahoma", Font.PLAIN, 16));
			btnNovo.setIcon(new ImageIcon(FrmOpcao.class.getResource("/com/sun/java/swing/plaf/windows/icons/Inform.gif")));
			btnNovo.setText("Jogar");
			btnNovo.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					FrmJogoNovo app= new FrmJogoNovo();
					app.setFrmOpcao( getFrmOpcao() );
	                app.setVisible(true);				
				}
			});
			panel.add(btnNovo);
			
			JButton btnSobre = new JButton();
			btnSobre.setIcon(new ImageIcon(FrmOpcao.class.getResource("/com/sun/javafx/scene/web/skin/Paste_16x16_JFX.png")));
			btnSobre.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent arg0) {
					FrmSobre frmSobre= new FrmSobre();
					frmSobre.setVisible(true);
				}
			});
			btnSobre.setText("Sobre");
			btnSobre.setFont(new Font("Tahoma", Font.PLAIN, 16));
			btnSobre.setBounds(409, 151, 147, 90);
			panel.add(btnSobre);
			
			JButton btnSair = new JButton();
			btnSair.setIcon(new ImageIcon(FrmOpcao.class.getResource("/com/sun/java/swing/plaf/windows/icons/Error.gif")));
			btnSair.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					System.exit(0);
				}
			});
			btnSair.setText("Sair");
			btnSair.setFont(new Font("Tahoma", Font.PLAIN, 16));
			btnSair.setBounds(409, 279, 147, 90);
			panel.add(btnSair);
			
			JLabel lblFootline = new JLabel("Footline");
			lblFootline.setForeground(Color.WHITE);
			lblFootline.setFont(new Font("Ink Free", Font.BOLD | Font.ITALIC, 60));
			lblFootline.setBounds(10, 11, 274, 65);
			panel.add(lblFootline);
			
			JLabel lblImgCopa = new JLabel("");
			lblImgCopa.setHorizontalAlignment(SwingConstants.CENTER);
	//		String strPath = Constantes.FILE_PATH + 
	//				File.separator + "imagens"+ File.separator;
			
			lblImgCopa.setIcon(new ImageIcon(FrmOpcao.class.getResource("/imagens/copa2018.jpg")));
			
			//lblImgArruda.setIcon(new ImageIcon(FrmOpcao.class.getResource("/javax/swing/plaf/basic/icons/JavaCup16.png")));
			lblImgCopa.setBounds(10, 94, 389, 285);
			panel.add(lblImgCopa);
			getContentPane().setLayout(groupLayout);
	
			pack();
			
		} catch (NumberFormatException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (ArquivoNaoEncontradoException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (RegistroNaoEncontradoException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}

	FrmOpcao getFrmOpcao() {
		return this;
	}
}
